CREATE TABLE talent_entity
(
    talent_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name  VARCHAR(255),
    mail       VARCHAR(255),
    password   VARCHAR(255),
    age        INT,
    avatar_url VARCHAR(255),
    education  VARCHAR(255),
    experience VARCHAR(255),
    CONSTRAINT pk_talententity PRIMARY KEY (talent_id)
);
----------------------------------------------------------
CREATE TABLE position_entity
(
    id_position       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    position          VARCHAR(255),
    talent_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_positionentity PRIMARY KEY (id_position)
);

ALTER TABLE position_entity
    ADD CONSTRAINT FK_POSITIONENTITY_ON_TALENT FOREIGN KEY (talent_id) REFERENCES talent_entity (talent_id);
-----------------------------------------------
