CREATE TABLE talent_entity
(
    talent_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name  VARCHAR(255),
    mail       VARCHAR(255),
    password   VARCHAR(255),
    age        INT,
    avatar_url VARCHAR(255),
    education  VARCHAR(255),
    experience VARCHAR(255),
    CONSTRAINT pk_talententity PRIMARY KEY (talent_id)
);

CREATE TABLE position_entity
(
    position_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    position    VARCHAR(255),
    CONSTRAINT pk_positionentity PRIMARY KEY (position_id)
);

CREATE TABLE role
(
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role    VARCHAR(20),
    CONSTRAINT pk_role PRIMARY KEY (role_id)
);

CREATE TABLE talent_position
(
    position_id BIGINT NOT NULL,
    talent_id   BIGINT NOT NULL,
    CONSTRAINT pk_talent_position PRIMARY KEY (position_id, talent_id)
);

CREATE TABLE talent_role
(
    role_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    talent_id BIGINT NOT NULL,
    CONSTRAINT pk_talent_role PRIMARY KEY (role_id, talent_id)
);

ALTER TABLE talent_position
    ADD CONSTRAINT fk_talpos_on_position_entity FOREIGN KEY (position_id) REFERENCES position_entity (position_id);

ALTER TABLE talent_position
    ADD CONSTRAINT fk_talpos_on_talent_entity FOREIGN KEY (talent_id) REFERENCES talent_entity (talent_id);

ALTER TABLE talent_role
    ADD CONSTRAINT fk_talrol_on_role FOREIGN KEY (role_id) REFERENCES role (role_id);

ALTER TABLE talent_role
    ADD CONSTRAINT fk_talrol_on_talent_entity FOREIGN KEY (talent_id) REFERENCES talent_entity (talent_id);

